config/routes.rb
ODC::Application.routes.draw do
  root "home#frontpage"

  #Users
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  match '/users/:id/presentations' => 'users#show_presentations', via: [:get]
  match '/users/:id/files' => 'users#show_files', via: [:get]
  resources :users
  match '/users' => 'users#index', via: [:get]

  #Newsletters
  match '/newsletters/unsubscribe' => 'newsletters#unsubscribe', via: [:get]
  match '/newsletters/perform_unsubscribe' => 'newsletters#perform_unsubscribe', via: [:get]
  resources :newsletters
  match '/newsletter_count' => 'newsletters#calculate_newsletter_recipients', via: [:post]
  match '/newsletter_authoring_tool' => 'newsletters#builder', via: [:get]

  #Courses
  resources :courses
  match '/vamping' => 'courses#show', :defaults => { :id => '45' },  via: [:get]
  match '/webinars', to: 'courses#webinars', via: [:get]
  match '/all_courses', to: 'courses#all_courses', via: [:get]
  match 'courses/:id/enrollments' => 'courses#enrollments', via: [:get]
  match 'courses/:id/enroll' => 'courses#enroll', via: [:post]
  match 'courses/:id/unenroll' => 'courses#unenroll', via: [:post]
  match 'courses/:id/rate' => 'courses#rate', via: [:post]
  match '/menrollment' => 'courses#menrollment', via: [:get]
  match '/menrollment' => 'courses#menrollment_create', via: [:post]
  match '/metrics' => 'courses#metrics', via: [:get]

  #Locale
  match '/change_locale', to: 'locales#change_locale', via: [:get]

  #Thumbnails
  match '/thumbnails' => 'presentations#presentation_thumbnails', via: [:get]

  #Tags
  match "/tags" => 'tags#index', :via => :get

  #Search
  match "/search" => 'search#index', :via => :get
  match "/search_teachers" => 'search#teacher_search', :via => :get
  
  #Terms of use
  match '/terms_of_use', to: "application#terms_of_use", via: [:get]
  match '/help', to: "home#help", via: [:get]
  match '/about', to: "home#about", via: [:get]

  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  get "/robots.:format", to: "sitemaps#robots"

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  #Wildcard route (This rule should be placed the last)
  match "*not_found", :to => 'errors#not_found', via: [:get]
end

app/views/layouts/_cropper_buttons.erb
<button type="button" class="btn btn-secondary btn-icon btn-sm btn-cropper delete-cropper">
	<span class="fas fa-trash"></i>
</button>
<button type="button" class="btn btn-secondary btn-icon btn-sm btn-cropper reset-cropper" style="display: none;">
    <span class="fas fa-redo"></i>
</button>

app/views/layouts/_footer.html.erb
<footer class="o-footer clearfix orange-footer" role="contentinfo">
	<div class="o-footer-bottom clearfix pb-5 pb-md-3">
		<div class="container">
			<ul class="nav float-left" style="align-items: flex-end;">
				<li class="nav-item">
					<a class="nav-link" target="_blank" href="http://www.fundacionorange.es/"><img src="/img/LogoFundacion.png" alt="" style="width: 180px; height: 47.5px; padding-bottom: 2px;"></a>
				</li>
				<hr>
				<hr>
				<li class="nav-item">
					<a class="nav-link" target="_blank" href="http://www.fundacionorange.es/politica-de-privacidad/"><%=t('cookies.privacy_policy')%></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" target="_blank" href="http://www.fundacionorange.es/politica-de-cookies/"><%=t('cookies.cookie_policy')%></a>
				</li>
				
				<li class="nav-item">
					<a class="nav-link" href="#" onclick="privacy(event)" ><%=t('cookies.more')%></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/about" ><%=t('about.title')%></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/help" ><%=t('help')%></a>
				</li>
			</ul>
				<div class="social-icons float-right mt-2" style="margin-top: 1rem !important;">
					<a class="btn btn-inverse btn-social btn-facebook" href="https://www.facebook.com/fundacionorange/" aria-label="Facebook" target="_blank"></a>
					<a class="btn btn-inverse btn-social btn-twitter" href="https://twitter.com/fundacionorange/" aria-label="Twitter" target="_blank"></a>
					<a class="btn btn-inverse btn-social btn-linkedin" href="https://www.linkedin.com/company/fundacionorange/" aria-label="Linkedin" target="_blank"></a>
					<a class="btn btn-inverse btn-social btn-instagram" href="https://www.instagram.com/FundacionOrange/" aria-label="Instagram" target="_blank"></a>
			</div>
		</div>
		

	</div>
	<%= render partial: "home/cookies", :locals => {} %>
</footer>

app/views/layouts/_form_field.erb
<div class="form-group row">
	<label for="inputDuration" class="col-12 col-sm-2 col-form-label <%=required ? "is-required":"" %>"><%=label%></label>
	<div class="col-12 col-sm-10">
		<%if type == "textarea" %>
			<textarea  class="form-control" autocomplete="off" name="<%=name%>" id="<%=id%>" placeholder="<%=placeholder %>" required="<%=defined?(required) and required == true%>"rows="6" ><%=value%></textarea>
		<%else%>
			<input type="<%=type%>" name="<%=name%>" <%=defined?(data_role) ? "data-role=#{data_role}": ''%> autocomplete="off" class="form-control" id="<%=id%>" placeholder="<%=placeholder %>" value="<%=value%>" <%=defined?(required) and required == true ? "required":""%> <%= (defined?(disabled) and disabled == true) ? "disabled" : "" %> <%= (defined?(checked) and checked == true) ? "checked" : "" %> min=0>
		<%end%>
	</div>
</div>

app/views/layouts/_form_field_icon.erb
<div class="input-group input-group-addon-float">
    <span class="input-group-addon "><i class="<%=icon%>"></i></span>
    <%if type == "textarea" %>
		<textarea  class="form-control" name="<%=name%>" autocomplete="off" id="<%=id%>" placeholder="<%=placeholder %>" rows="3"><%=value%></textarea>
	<%else%>
		<input type="<%=type%>" name="<%=name%>" autocomplete="off" class="form-control" id="<%=id%>" placeholder="<%=placeholder %>" value="<%=value%>" >
	<%end%>
	<%if defined? delete%>
    	<span class="input-group-addon input-group-addon-right <%=delete%>">
    		<i class="far fa-trash-alt"></i>
    	</span>
    <%end%>
</div>

app/views/layouts/_header.html.erb
<nav class=" navbar navbar-expand-md navbar-dark bg-dark2 <%=@searching ? "search" : ""%>">
	<div class="container-fluid">
	<a class="navbar-brand" href="/">
		<img class="navbar-logo" src="/img/orange_logo.svg" alt=""/> <span class="navbar-brand-title h1 mb-0">  Digital Center </span>
	</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item ">
				<a class="nav-link text-center <%=current_page?("/") ? "active" : ""%>" href="/">
					<span class="d-none d-sm-none d-md-inline d-lg-inline d-xl-none">
						<i class="navbar-icon fas fa-home"></i>
					</span>
					<span class="d-inline d-sm-inline d-md-none d-lg-none d-xl-inline">
						<%= t('navbar.home') %>
					</span>
				</a>
			</li>
			<li class="nav-item ">
				<a class="nav-link text-center <%=current_page?("/courses") ? "active" : ""%>" href="/courses">
					<span class="d-none d-sm-none d-md-inline d-lg-inline d-xl-none">
						<i class="navbar-icon fas fa-book"></i>
					</span>
					<span class="d-inline d-sm-inline d-md-none d-lg-none d-xl-inline">
						<%= t('navbar.courses') %>
					</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link text-center  <%=current_page?("/webinars") ? "active" : ""%>" href="/webinars">
					<span class="d-none d-sm-none d-md-inline d-lg-inline d-xl-none">
						<i class="navbar-icon fas fa-podcast"></i>
					</span>
					<span class="d-inline d-sm-inline d-md-none d-lg-none d-xl-inline">
						<%= t('navbar.webinars') %>
					</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link text-center  <%=current_page?("/about") ? "active" : ""%>" href="/about">
					<span class="d-none d-sm-none d-md-inline d-lg-inline d-xl-none">
						<i class="navbar-icon fas fa-info"></i>
					</span>
					<span class="d-inline d-sm-inline d-md-none d-lg-none d-xl-inline">
						<%= t('about.title') %>
					</span>
				</a>
			</li>
			<%if user_signed_in? && current_user.isAdmin? %>
			<li class="nav-item dropdown">
				<a class="nav-link text-center dropdown-toggle" data-target="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<span class="d-none d-sm-none d-md-inline d-lg-inline d-xl-none orange"><i class="navbar-icon fas fa-cog"></i></span>
					<span class="d-inline d-sm-inline d-md-none d-lg-none d-xl-inline none orange">Admin</span>
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="/courses/new"><%= t('navbar.new_course') %></a>
					<a class="dropdown-item" href="/courses/new?webinar=1"><%= t('navbar.new_webinar') %></a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="/menrollment"><%= t('course.massive_enrollment') %></a>
					<a class="dropdown-item" href="/newsletters"><%= t('email.massive_email') %></a>
					<div class="dropdown-divider"></div>

					<a class="dropdown-item" href="/metrics"><%= t('course.metrics.title') %></a>
					<a class="dropdown-item" href="/users"><%= t('user.users') %></a>
				</div>
			</li>
			<%end%>
		</ul>
		<% unless (@searching) || (user_signed_in? && current_user.isAdmin?) %>
		<form class="form-inline my-2 my-lg-0 search-bar d-none d-lg-inline" action="/search">
			<input class="form-control mr-sm-2 search-bar input input-search" name="q" placeholder="" aria-label="<%= t('navbar.search') %>" type="dsearch" autocomplete="off">
			<button class="btn my-2 my-sm-0 btn-link btn-search" type="submit"><img src="/img/search_ES.svg" class="search-icon"/></button>
		</form>
		<% end %>
		<ul class="navbar-nav lang">
			<li class="nav-item user">
			<%if user_signed_in?%>
			<div class="user-name-container">
				<a class="user-profile" href="<%=user_path(current_user)%>">
					<img src="<%=current_user.avatar.url || "/img/user_placeholder.png" %>" class="user-img"/>
					<span class="nav-link user-name "><%=current_user[:name]%></span>
				</a></div>
				<%else%>
				<%= link_to "", new_user_session_url, class: "nav-link icon-my-account d-md-block"%>
				<%end%>
			</li>

			<% I18n.available_locales.map(&:to_s).each do |lanCode| %>
			<form class="change_locale" action="/change_locale" action="GET" class="lang nav-item ">
				<input name="locale" value="" type="hidden"/>
				<li class="nav-item <%= t('lang') == lanCode ? "active":""%>" value="<%=lanCode%>">
					<a class="nav-link"><%=lanCode%>
					</a>
				</li>
			</form>
			<% end %>

		</ul>
	</div>
	</div>
</nav>

app/views/layouts/_input_file_custom.erb
<div class="custom-file">
	<label class="custom-file-label" for="customFile">
		<%if file_name %>
			<%file_name  = file_name == "data" ? "image.png" : file_name%>
			<a href="<%=file_path%>" download="<%=file_name%>" onclick="event.stopPropagation()"><%=file_name%></a>
		<%else%>
			<%=defined?(local_assigns[:label]) ? local_assigns[:label] : t('course.upload')%>
		<%end%>
	</label>
	<input type="file" accept="<%=defined?( accept ) ? accept : "*"%>" class="custom-file-input" name="<%=name%>" id="<%=id%>" <%=defined?(data_img_id) ? ("data-img-id=#{data_img_id}")  : '' %>  <%=defined?(width) ? ("data-w=#{width}") : '' %> <%=defined?(height) ? ("data-h=#{height}") : "" %> <%=defined?(data_name) ? ("data-name=#{data_name}") : "" %> 
	>
</div>

app/views/layouts/_login_dropdown.html.erb
<div class="dropdown-menu dropdown-menu-right dropdown-login" aria-labelledby="loginDropdown">
	<%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: 'custom-form px-4 py-4', id:"loginForm", method: "post", onclick: "event.stopPropagation()" }) do |f| %>
	<div class="form-group" >
		<label for="email"><%= t("user.email")%></label>
		<input type="email" class="form-control" id="email" placeholder="" required name="user[email]">
	</div>
	<div class="form-group">
		<label for="password"><%= t("user.password")%></label>
		<input type="password" class="form-control" id="password" placeholder="" required name="user[password]">
	</div>
	<div class="form-check custom-checkbox">
		<input type="checkbox" class="custom-control-input" id="dropdownCheck" name="user[remember_me]">
		<label class="custom-control-label" for="dropdownCheck">
			<%= t("navbar.remember")%>
		</label>
	</div>
	<br>
	<a class="dropdown-item px-0 text-underline" href="/users/password/new"><%= t("navbar.forgot")%></a>
	<a class="dropdown-item px-0" href="/users/sign_up"><%= t("navbar.signup")%></a>
	
	<br>
	<div class="text-right">
		<input type="submit" name="commit" class="btn btn-outline-dark" value="<%= t("navbar.login")%>" />
	</div>
	<%end%>
</div>
<script>
</script>

app/views/layouts/_notification.html.erb
<% alertType ||= "danger" %>
<% alertClass = (alertType=="success") ? "alert-success" : ((alertType=="warning") ? "alert-warning" : "alert-danger") %>
<% dismissable ||= true %>
<% dismissableClass = (dismissable==true) ? "alert-dismissable" : "" %>

<div class="alert <%=alertClass=%> <%=dismissableClass%> ">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
	<span class="text"><%= msg %></span>
</div>

app/views/layouts/_notifications.html.erb
<div id="layout_notifications">
	<% if flash[:notice] %>
		<% if flash[:notice].is_a? Array %>
			<% flash[:notice].uniq! %>
			<% flash[:notice].each do |msg| %>
				<%= render '/layouts/notification', :alertType => "success", :msg => msg %>
			<% end %>
		<% else %>
			<%= render '/layouts/notification', :alertType => "success", :msg => flash[:notice] %>
		<% end %>
	<% end %>

	<% if flash[:alert] %>
		<% if flash[:alert].is_a? Array %>
			<% flash[:alert].uniq! %>
			<% flash[:alert].each do |msg| %>
				<%= render '/layouts/notification', :alertType => "danger", :msg => msg %>
			<% end %>
		<% else %>
			<%= render '/layouts/notification', :alertType => "danger", :msg => flash[:alert] %>
		<% end %>
	<% end %>

	<% if flash[:warning] %>
		<% if flash[:warning].is_a? Array %>
			<% flash[:warning].uniq! %>
			<% flash[:warning].each do |msg| %>
				<%= render '/layouts/notification', :alertType => "warning", :msg => msg %>
			<% end %>
		<% else %>
			<%= render '/layouts/notification', :alertType => "warning", :msg => flash[:warning] %>
		<% end %>
	<% end %>
</div>

app/views/layouts/_seo.html.erb
<%title = defined?(@course) ? @course.name : "Orange Digital Center"%>
<%author = (defined?(@course) and !@course.powered_by.blank?) ? @course.powered_by : "Orange"%>
<%description = (defined?(@course) and !@course.description.blank?) ? (strip_tags(@course.description).html_safe) : t("landing.intro_new") %>
<%@host = request.protocol + request.host_with_port %>
<%img = (defined?(@course) and !@course.thumb_file_name.blank?) ? (@host + @course.thumb.url) : nil%>
<%course_item_list = @top_courses || @top_webinars || @courses%>
<title><%=title%></title> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="<%=description%>"/>
<meta name="author" content="<%=author%>" />
<meta name="title" content="<%=title%>">

<meta name="keywords" content="Orange, RSC, Cursos, Courses, Educación, Education, Formación, Training"/>
<meta name="geo.region" content="ES"/>
<meta name="resource-type" content="document"/>
<meta name="theme-color" content="#ffffff">


<!-- Schema.org markup for Google+ -->
<meta itemprop="name" content="<%=title%>"/>
<meta itemprop="description" content="<%=description%>"/>
<%if img%>
	<meta itemprop="image" content="<%=img%>">
<%end%>
<%if defined?(@course) and @course.id%>
	<script type="application/ld+json">
	{
		"@context": "https://schema.org/",
		"@type": "Course",
		"name": "<%=title%>",
		<%if !img.blank?%>
		"thumbnailUrl": "<%=img%>",
		<%end%>
		"keywords": "<% (@course[:categories]||[]).each_with_index{|tag, index|%><%=t("categories." + tag)%><%if index != @course[:categories].length()-1%>,<%end%><%}%>",
		<% if defined?(@course) and !@course.dedication.blank? %>
		"courseWorkload": "<%=@course.dedication%>",
		<%end%>
		<% if defined?(@course) and !@course.rating.blank? %>
		"aggregateRating": {
		  "@type": "AggregateRating",
		  "ratingValue": "<%=@course.rating%>"
		  "ratingCount": <%=@course.ratings.length%>
		},
		<%end%>
		"eventAttendanceMode": "online",
		"description": "<%=description%>",
		"datePublished": "<%=to_seo_datetime(@course.created_at)%>",
		"dateModified": "<%=to_seo_datetime(@course.updated_at)%>",
		"url": "<%=@host%>/courses/<%=@course.id%>",
		"provider": {
			"@type": "Organization",
			"name": "<%=author%>"
		},
		<%teachers = @course.sorted_teachers||[]%>
		"instructor": [<% (teachers).each_with_index{|teacher, index|%>
          {
            "@type": "Person",
            "name": "<%=teacher.name%>",
            "jobTitle": "<%=teacher.position_en%>",
            "image": "<%=@host%><%=teacher.avatar.url%>"
          }<%if index != teachers.length()-1%>,<%end%>
        <%}%>],
		"hasCourseInstance": {
		    "@type": "CourseInstance",
		    "courseMode": [<% if !@course.format.blank?%>"<%=@course.format%>",<%elsif @course.webinar%>"webinar",<%end%>"online"],
		    "startDate": "<%=to_ymd(@course.start_date)%>",
		    "endDate": "<%=to_ymd(@course.end_date)%>"
		  }
	}
	</script>
<%else%>
	<script type="application/ld+json">
	{
      "@context": "https://schema.org",
      "@type": "WebSite",
      "url": "<%=@host%>",
      "potentialAction": {
        "@type": "SearchAction",
        "target": "<%=@host%>/search?q={search_term_string}",
        "query-input": "required name=search_term_string"
      }
    }
	</script>
<%end%>
<!-- Twitter Card data -->
<meta name="twitter:card" content="summary"/>
<meta name="twitter:site" content="@orange_es"/>
<meta name="twitter:title" content="<%=title%>"/>
<meta name="twitter:description" content="<%=description%>"/>
<meta name="twitter:creator" content="@orange_es"/>
<!-- Twitter summary card with large image must be at least 280x150px -->
<%if img%>
	<meta name="twitter:image:src" content="<%=img%>">
	<meta name="twitter:image" content="<%=img%>">
<%end%>
<!-- Open Graph data -->
<meta property="og:title" content="<%=title%>" />
<meta property="og:type" content="school" />
<meta property="og:url" content="<%=request.original_url %>" />
<%if img%>
	<meta property="og:image" content="<%=img%>">
<%end%>
<meta property="og:description" content="<%=description%>" />
<meta property="og:site_name" content="Orange Digital Center" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%=render partial: "layouts/seo" %>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="/fontawesome-free-5.13.1-web/css/all.min.css" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boosted@4.5.2/dist/css/orangeHelvetica.min.css" integrity="sha384-ZWV5rANfkZIt/7HDFToWXT+5LfpEbtDN22vw9WhARiDc+o6zJ4qxwdTwskCbe8NK" crossorigin="anonymous">
	<!-- Copyright © 2016 Orange SA. All rights reserved -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boosted@4.5.2/dist/css/orangeIcons.min.css" integrity="sha384-R6GN9ea/4pryAfJqIKDPT52rqJuxaMkZndUr7tl6YQmESyczsGyDgIbpuXvebpF5" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boosted@4.5.2/dist/css/boosted.min.css" integrity="sha384-j8BgukP8/Cao3CDMrwvCOSDGFQr7Yr3LGW9PUWByAoJuSwmgppSVBjC8rOSubbeC" crossorigin="anonymous">

	<script src="/ckeditor4/ckeditor.js"></script>
	<%= stylesheet_link_tag    'application', media: 'all'%>
	<%= javascript_include_tag 'application' %>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.1/js/jquery.tablesorter.min.js" integrity="sha384-QnFIXbEfAgO7z63b/aNzTSdSNLoNiNX/mk/Ok+NpUNMnvriWLo5cOtB0OUCAdKNu" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/boosted@4.5.2/dist/js/boosted.min.js" integrity="sha384-Ochdn7tEptQMWvKZ+UJHlK48cRq+lpQfD+cvNHas5cOG62XdpPFzZDjO303+fISm" crossorigin="anonymous"></script>

	<%= csrf_meta_tags %>
	<%= favicon_link_tag "/assets/favicon.ico" %>
	<meta charset="UTF-8">
</head>
<body>
	<div id="wrapper">
		<%= render partial: "layouts/header", :locals => {}  %>
		<%= render '/layouts/notifications' %>
		<%= yield %>
		<%= render "layouts/footer" %>
	</div>
</body>
</html>

app/views/layouts/iframe.full.erb
<!DOCTYPE html>
<html>
  <head>
    <%if @title%>
      <title><%=@title%></title>
    <% end %>
    <%= favicon_link_tag "/assets/favicon.ico" %>
    <meta charset="UTF-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <style type="text/css">
      html, body {
        width: 100%;
        height: 100%;
        overflow: hidden;
        margin: 0px !important;
      }
    </style>
    <%= yield :headers %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>